USE Control_Escolar
GO

/*
Prueba tecnica
Autor: FJRL
Fecha: 1/09/2026
Create Tables - Contingencia
*/

BEGIN TRANSACTION;
	BEGIN TRY
		IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Alumno' AND TABLE_SCHEMA = 'dbo')
		BEGIN
			DROP TABLE dbo.Alumno;
			PRINT 'Tabla Alumno eliminada';
		END
	COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
	IF @@TRANCOUNT > 0
		ROLLBACK TRANSACTION;
		THROW;
	END CATCH
GO
